import type { ReportResponse } from "./report";

const FIXTURE_TIMESTAMP = "2026-08-02T14:30:00Z";

export const reportFixture = {
  report: {
    report_id: "rpt_mvp_visibility",
    research_run_id: "rr_mvp_visibility",
    question: "근거가 부족한 주장과 뒷받침하는 원문을 어떻게 보여줄까요?",
    title: "근거를 확인하는 보고서",
    status: "ready",
    markdown: [
      "# 근거를 확인하는 보고서",
      "",
      "근거가 부족한 주장도 **결과에서 숨기지 않습니다**.",
      "",
      "각 문장에서 주장, 근거, 원문으로 이어지는 확인 경로를 볼 수 있습니다.",
      "",
      "## 읽는 방법",
      "",
      "- 보고서 내용을 먼저 읽습니다.",
      "- 확인이 필요한 문장에서 연결된 근거를 엽니다.",
      "- ‘근거 부족’은 정보가 사라진 것이 아니라 추가 확인이 필요한 상태입니다.",
    ].join("\n"),
    created_at: FIXTURE_TIMESTAMP,
    statements: [
      {
        statement_id: "stmt_supported_visibility",
        report_id: "rpt_mvp_visibility",
        claim_id: "clm_supported_visibility",
        position: 0,
        text: "근거가 부족한 주장도 결과에서 숨기지 않습니다.",
        created_at: FIXTURE_TIMESTAMP,
      },
      {
        statement_id: "stmt_supported_traceability",
        report_id: "rpt_mvp_visibility",
        claim_id: "clm_supported_traceability",
        position: 1,
        text: "각 문장에서 주장, 근거, 원문으로 이어지는 확인 경로를 볼 수 있습니다.",
        created_at: FIXTURE_TIMESTAMP,
      },
      {
        statement_id: "stmt_unsupported_latency",
        report_id: "rpt_mvp_visibility",
        claim_id: "clm_unsupported_latency",
        position: 2,
        text: "MVP가 조사 완료 시간을 항상 일정하게 보장합니다.",
        created_at: FIXTURE_TIMESTAMP,
      },
    ],
    claims: [
      {
        claim_id: "clm_supported_visibility",
        research_run_id: "rr_mvp_visibility",
        text: "근거가 부족한 주장도 ‘근거 부족’ 상태로 계속 표시합니다.",
        status: "supported",
        confidence: 0.93,
        created_at: FIXTURE_TIMESTAMP,
      },
      {
        claim_id: "clm_supported_traceability",
        research_run_id: "rr_mvp_visibility",
        text: "보고서 문장은 주장에 연결되고, 주장은 근거를 거쳐 원문으로 이어집니다.",
        status: "supported",
        confidence: 0.88,
        created_at: FIXTURE_TIMESTAMP,
      },
      {
        claim_id: "clm_unsupported_latency",
        research_run_id: "rr_mvp_visibility",
        text: "MVP가 조사 완료 시간을 항상 일정하게 보장합니다.",
        status: "unsupported",
        confidence: 0.2,
        created_at: FIXTURE_TIMESTAMP,
      },
    ],
    evidence: [
      {
        evidence_id: "ev_visibility_rule",
        source_id: "src_project_agents",
        research_run_id: "rr_mvp_visibility",
        kind: "summary",
        quote_or_summary: "프로젝트 규칙은 근거가 부족한 주장도 숨기지 않고 상태를 표시하도록 합니다.",
        locator: "AGENTS.md#basic-principles",
        collected_at: FIXTURE_TIMESTAMP,
        content_hash: "sha256:1111111111111111111111111111111111111111111111111111111111111111",
      },
      {
        evidence_id: "ev_traceability_contract",
        source_id: "src_design_traceability",
        research_run_id: "rr_mvp_visibility",
        kind: "summary",
        quote_or_summary: "보고서 문장에서 주장, 근거, 원문으로 이어지는 확인 경로를 제공합니다.",
        locator: "DESIGN.md#information-architecture",
        collected_at: FIXTURE_TIMESTAMP,
        content_hash: "sha256:2222222222222222222222222222222222222222222222222222222222222222",
      },
    ],
    sources: [
      {
        source_id: "src_project_agents",
        research_run_id: "rr_mvp_visibility",
        source_type: "document",
        title: "ClaimGraph 사용 안내",
        locator: "https://claimgraph.local/AGENTS.md",
        source_url: "https://claimgraph.local/AGENTS.md",
        publisher: "ClaimGraph",
        retrieved_at: FIXTURE_TIMESTAMP,
        content_hash: "sha256:3333333333333333333333333333333333333333333333333333333333333333",
      },
      {
        source_id: "src_design_traceability",
        research_run_id: "rr_mvp_visibility",
        source_type: "document",
        title: "ClaimGraph 화면 설계 안내",
        locator: "https://claimgraph.local/DESIGN.md",
        source_url: "https://claimgraph.local/DESIGN.md",
        publisher: "ClaimGraph",
        retrieved_at: FIXTURE_TIMESTAMP,
        content_hash: "sha256:4444444444444444444444444444444444444444444444444444444444444444",
      },
    ],
    claim_evidence_relations: [
      {
        relation_id: "rel_visibility_rule",
        claim_id: "clm_supported_visibility",
        evidence_id: "ev_visibility_rule",
        relation_type: "supports",
        confidence: 0.93,
        created_at: FIXTURE_TIMESTAMP,
      },
      {
        relation_id: "rel_traceability_contract",
        claim_id: "clm_supported_traceability",
        evidence_id: "ev_traceability_contract",
        relation_type: "supports",
        confidence: 0.88,
        created_at: FIXTURE_TIMESTAMP,
      },
    ],
  },
} satisfies ReportResponse;

export const unsupportedReportFixture = {
  report: {
    report_id: "rpt_unsupported_only",
    research_run_id: "rr_unsupported_only",
    question: "근거가 없는 주장도 결과에 남겨 둘 수 있을까요?",
    title: "근거 부족 상태 확인",
    status: "draft",
    markdown: [
      "# 근거 부족 상태 확인",
      "",
      "이 예시에서는 연결된 근거가 없는 주장도 결과에서 숨기지 않습니다.",
    ].join("\n"),
    created_at: FIXTURE_TIMESTAMP,
    statements: [
      {
        statement_id: "stmt_unsupported_only",
        report_id: "rpt_unsupported_only",
        claim_id: "clm_unsupported_only",
        position: 0,
        text: "연결된 근거가 없는 주장도 결과에서 확인할 수 있습니다.",
        created_at: FIXTURE_TIMESTAMP,
      },
    ],
    claims: [
      {
        claim_id: "clm_unsupported_only",
        research_run_id: "rr_unsupported_only",
        text: "이 주장은 연결된 근거가 없어 ‘근거 부족’으로 표시합니다.",
        status: "unsupported",
        confidence: 0.1,
        created_at: FIXTURE_TIMESTAMP,
      },
    ],
    evidence: [],
    sources: [],
    claim_evidence_relations: [],
  },
} satisfies ReportResponse;
