import type { ReportResponse } from "./report";

const FIXTURE_TIMESTAMP = "2026-08-02T14:30:00Z";

export const reportFixture = {
  report: {
    report_id: "rpt_mvp_visibility",
    research_run_id: "rr_mvp_visibility",
    question: "How should the MVP expose report claims and their supporting evidence?",
    title: "MVP Claim Visibility",
    status: "ready",
    markdown: [
      "# MVP Claim Visibility",
      "",
      "The MVP keeps **unsupported claims visible** instead of removing them from the report.",
      "",
      "A reader can follow each supported statement through a Claim, a ClaimEvidenceRelation, Evidence, and a Source.",
      "",
      "## Reading rule",
      "",
      "- Read the report body first.",
      "- Open the Claim trace when a sentence needs checking.",
      "- Treat `unsupported` as an explicit review state, not as a missing row.",
    ].join("\n"),
    created_at: FIXTURE_TIMESTAMP,
    statements: [
      {
        statement_id: "stmt_supported_visibility",
        report_id: "rpt_mvp_visibility",
        claim_id: "clm_supported_visibility",
        position: 0,
        text: "The MVP keeps unsupported claims visible instead of removing them from the report.",
        created_at: FIXTURE_TIMESTAMP,
      },
      {
        statement_id: "stmt_supported_traceability",
        report_id: "rpt_mvp_visibility",
        claim_id: "clm_supported_traceability",
        position: 1,
        text: "Each supported report statement can be traced through Claim, Evidence, and Source IDs.",
        created_at: FIXTURE_TIMESTAMP,
      },
      {
        statement_id: "stmt_unsupported_latency",
        report_id: "rpt_mvp_visibility",
        claim_id: "clm_unsupported_latency",
        position: 2,
        text: "The MVP currently guarantees a fixed end-to-end research latency target.",
        created_at: FIXTURE_TIMESTAMP,
      },
    ],
    claims: [
      {
        claim_id: "clm_supported_visibility",
        research_run_id: "rr_mvp_visibility",
        text: "Unsupported claims remain visible with unsupported status.",
        status: "supported",
        confidence: 0.93,
        created_at: FIXTURE_TIMESTAMP,
      },
      {
        claim_id: "clm_supported_traceability",
        research_run_id: "rr_mvp_visibility",
        text: "Report statements reference Claims, Claims connect to Evidence through relations, and Evidence references Sources.",
        status: "supported",
        confidence: 0.88,
        created_at: FIXTURE_TIMESTAMP,
      },
      {
        claim_id: "clm_unsupported_latency",
        research_run_id: "rr_mvp_visibility",
        text: "The MVP currently guarantees a fixed end-to-end research latency target.",
        status: "unsupported",
        confidence: 0.2,
        created_at: FIXTURE_TIMESTAMP,
      },
    ],
    evidence: [
      {
        evidence_id: "ev_visibility_rule",
        source_id: "src_project_agents",
        research_run_id: "rr_mvp_visibility",
        kind: "summary",
        quote_or_summary: "Project rules require unsupported claims to be shown as unsupported instead of hidden.",
        locator: "AGENTS.md#basic-principles",
        collected_at: FIXTURE_TIMESTAMP,
        content_hash: "sha256:1111111111111111111111111111111111111111111111111111111111111111",
      },
      {
        evidence_id: "ev_traceability_contract",
        source_id: "src_design_traceability",
        research_run_id: "rr_mvp_visibility",
        kind: "summary",
        quote_or_summary: "The report UI starts at ReportStatement and traces Claim, ClaimEvidenceRelation, Evidence, and Source IDs.",
        locator: "DESIGN.md#information-architecture",
        collected_at: FIXTURE_TIMESTAMP,
        content_hash: "sha256:2222222222222222222222222222222222222222222222222222222222222222",
      },
    ],
    sources: [
      {
        source_id: "src_project_agents",
        research_run_id: "rr_mvp_visibility",
        source_type: "document",
        title: "ClaimGraph repository instructions",
        locator: "https://claimgraph.local/AGENTS.md",
        source_url: "https://claimgraph.local/AGENTS.md",
        publisher: "ClaimGraph",
        retrieved_at: FIXTURE_TIMESTAMP,
        content_hash: "sha256:3333333333333333333333333333333333333333333333333333333333333333",
      },
      {
        source_id: "src_design_traceability",
        research_run_id: "rr_mvp_visibility",
        source_type: "document",
        title: "ClaimGraph Web UI design source of truth",
        locator: "https://claimgraph.local/DESIGN.md",
        source_url: "https://claimgraph.local/DESIGN.md",
        publisher: "ClaimGraph",
        retrieved_at: FIXTURE_TIMESTAMP,
        content_hash: "sha256:4444444444444444444444444444444444444444444444444444444444444444",
      },
    ],
    claim_evidence_relations: [
      {
        relation_id: "rel_visibility_rule",
        claim_id: "clm_supported_visibility",
        evidence_id: "ev_visibility_rule",
        relation_type: "supports",
        confidence: 0.93,
        created_at: FIXTURE_TIMESTAMP,
      },
      {
        relation_id: "rel_traceability_contract",
        claim_id: "clm_supported_traceability",
        evidence_id: "ev_traceability_contract",
        relation_type: "supports",
        confidence: 0.88,
        created_at: FIXTURE_TIMESTAMP,
      },
    ],
  },
} satisfies ReportResponse;

export const unsupportedReportFixture = {
  report: {
    report_id: "rpt_unsupported_only",
    research_run_id: "rr_unsupported_only",
    question: "Can an unsupported Claim remain visible without an Evidence link?",
    title: "Unsupported Claim Scenario",
    status: "draft",
    markdown: [
      "# Unsupported Claim Scenario",
      "",
      "This scenario keeps an unsupported Claim visible without attaching an Evidence relation.",
    ].join("\n"),
    created_at: FIXTURE_TIMESTAMP,
    statements: [
      {
        statement_id: "stmt_unsupported_only",
        report_id: "rpt_unsupported_only",
        claim_id: "clm_unsupported_only",
        position: 0,
        text: "This scenario keeps an unsupported Claim visible without attaching an Evidence relation.",
        created_at: FIXTURE_TIMESTAMP,
      },
    ],
    claims: [
      {
        claim_id: "clm_unsupported_only",
        research_run_id: "rr_unsupported_only",
        text: "The unsupported Claim is visible and has no ClaimEvidenceRelation.",
        status: "unsupported",
        confidence: 0.1,
        created_at: FIXTURE_TIMESTAMP,
      },
    ],
    evidence: [],
    sources: [],
    claim_evidence_relations: [],
  },
} satisfies ReportResponse;
